#!/bin/sh

. /etc/init.d/functions-ri

HOSTNAME=$(/bin/hostname)

hostname -b -F /etc/hostname 2> /dev/null

if [ $? -ne 0 ]; then
	# Busybox hostname doesn't support -b so we need implement it on our own
	if [ -f /etc/hostname ];then
		hostname `cat /etc/hostname` || exit 1
	elif [ -z "$HOSTNAME" -o "$HOSTNAME" = "(none)" -o ! -z "`echo $HOSTNAME | sed -n '/^[0-9]*\.[0-9].*/p'`" ] ; then
		hostname localhost || exit 1
	fi
fi

markran

exit 0
