#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/sbin

usecttyhack=""

[ -x "$(which cttyhack)" ] && usecttyhack=cttyhack

exec </dev/console >/dev/console 2>/dev/console

exec setsid $usecttyhack /bin/sh -l
